apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: federation-apiserver-etcd
  annotations:
    volume.alpha.kubernetes.io/storage-class: "yes"
  namespace: federation
  labels:
    app: federated-cluster
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
