apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: federation-controller-manager
  namespace: federation
  labels:
    app: federated-cluster
spec:
  template:
    metadata:
      name: federation-controller-manager
      labels:
        app: federated-cluster
        module: federation-controller-manager
    spec:
      volumes:
      - name: ssl
        hostPath:
          path: /etc/ssl
      containers:
      - name: controller-manager
        image: gcr.io/google_containers/hyperkube-amd64:v1.5.2
        args:
          - /hyperkube
          - federation-controller-manager
          - --master=https://federation-apiserver:443
          - --dns-provider=google-clouddns
          - --federation-name=federation
          - --zone-name=federation.com.
          - --v=2
        volumeMounts:
        - name: ssl
          readOnly: true
          mountPath: /etc/ssl
        ports:
          - containerPort: 443
            name: https
          - containerPort: 8080
            name: local
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
