apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: federation-apiserver
  namespace: federation
  labels:
    app: federated-cluster
spec:
  template:
    metadata:
      name: federation-apiserver
      labels:
        app: federated-cluster
        module: federation-apiserver
    spec:
      containers:
      - name: apiserver
        image: gcr.io/google_containers/hyperkube-amd64:v1.6.2
        env:
          - name: ADVERTISE_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: federated-apiserver
                key: advertise-address
        command:
          - /hyperkube
          - federation-apiserver
          - --bind-address=0.0.0.0
          - --etcd-servers=http://localhost:2379
          - --secure-port=443
          - --advertise-address=$(ADVERTISE_ADDRESS)
          - --token-auth-file=/srv/kubernetes/known-tokens.csv
        ports:
          - containerPort: 443
            name: https
          - containerPort: 8080
            name: local
        volumeMounts:
          - name: federation-apiserver-secrets
            mountPath: /srv/kubernetes/
            readOnly: true
      - name: etcd
        image: quay.io/coreos/etcd:v3.0.7
        command:
          - "/usr/local/bin/etcd"
        args:
          - "--data-dir=/var/lib/etcd"
        volumeMounts:
          - name: etcd-data
            mountPath: /var/lib/etcd
      volumes:
        - name: federation-apiserver-secrets
          secret:
            secretName: federation-apiserver-secrets
        - name: etcd-data 
          persistentVolumeClaim:
            claimName: federation-apiserver-etcd
